name: healthy_flutter_workspace
packages:
  - apps/healthy_meals
  - apps/healthy_workouts
  - packages/healthy_mobile_auth

command:
  version:
    # Placeholder group for future versioning
    scope: "**"
